# Generated by Django 6.0.6 on 2026-06-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("USER", "User"),
                    ("AGENT", "Agent"),
                    ("SUPERVISOR", "Supervisor"),
                    ("ADMIN", "Admin"),
                ],
                default="USER",
                max_length=20,
            ),
        ),
    ]
