# Generated by Django 6.0.6 on 2026-06-09 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
        ("tickets", "0003_alter_ticket_city_alter_ticket_country_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="state",
            name="country",
        ),
        migrations.DeleteModel(
            name="City",
        ),
        migrations.DeleteModel(
            name="Country",
        ),
        migrations.DeleteModel(
            name="State",
        ),
    ]
