# Generated by Django 6.0.6 on 2026-06-08 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="city",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="locations.city",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ticket",
            name="country",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="locations.country",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ticket",
            name="state",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="locations.state",
            ),
            preserve_default=False,
        ),
    ]
