# Generated by Django 6.0.6 on 2026-06-09 06:13
# Hand-edited: safe multi-step FK → CharField conversion.
#
# Strategy:
#   1. Add three new VARCHAR columns (country_new, state_new, city_new)
#   2. Populate them with name strings from the related location tables
#   3. Drop the old FK integer columns (country_id, state_id, city_id)
#   4. Rename the new columns to country, state, city

from django.db import migrations, models


def populate_text_columns(apps, schema_editor):
    """Copy name strings from location tables into the new text columns."""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            UPDATE tickets_ticket t
            SET country_new = lc.name
            FROM locations_country lc
            WHERE t.country_id = lc.id
        """)
        cursor.execute("""
            UPDATE tickets_ticket t
            SET state_new = ls.name
            FROM locations_state ls
            WHERE t.state_id = ls.id
        """)
        cursor.execute("""
            UPDATE tickets_ticket t
            SET city_new = lc.name
            FROM locations_city lc
            WHERE t.city_id = lc.id
        """)


class Migration(migrations.Migration):
    # atomic=False: required because PostgreSQL cannot ALTER TABLE within the
    # same transaction that just ran DML (RunPython triggers deferred FK events).
    # Each operation here commits independently — safe for a single-DB setup.
    atomic = False

    dependencies = [
        ("tickets", "0002_alter_ticket_city_alter_ticket_country_and_more"),
    ]

    operations = [
        # 1. Add temporary text columns
        migrations.AddField(
            model_name="ticket",
            name="country_new",
            field=models.CharField(max_length=100, default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ticket",
            name="state_new",
            field=models.CharField(max_length=100, default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ticket",
            name="city_new",
            field=models.CharField(max_length=100, default=""),
            preserve_default=False,
        ),
        # 2. Populate text columns from related location rows
        migrations.RunPython(
            populate_text_columns,
            reverse_code=migrations.RunPython.noop,
        ),
        # 3. Remove old FK columns
        migrations.RemoveField(model_name="ticket", name="country"),
        migrations.RemoveField(model_name="ticket", name="state"),
        migrations.RemoveField(model_name="ticket", name="city"),
        # 4. Rename new text columns to canonical names
        migrations.RenameField(model_name="ticket", old_name="country_new", new_name="country"),
        migrations.RenameField(model_name="ticket", old_name="state_new", new_name="state"),
        migrations.RenameField(model_name="ticket", old_name="city_new", new_name="city"),
    ]
