# Generated by Django 6.0.6 on 2026-06-09 11:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0003_alter_ticket_city_alter_ticket_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="last_action_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
